### ISSUE TITLE
Radar Chart

### ISSUE THREAD

**Issue by kaerumy** [Sinar/hr-censorship-dashboard#20]
A radar chart might be one way of displaying different categories of online censorship

Are there ready libraries for this?

![image](https://user-images.githubusercontent.com/1060743/41845927-bc9631d0-78a7-11e8-91b6-5c4e3863a2c7.png)

**Comment by Jeffrey04** [comment]
Just found this
https://www.primefaces.org/primereact/#/radarchart
this look interesting
