### ISSUE TITLE
Events content or data

### ISSUE THREAD

**Issue by kaerumy** [Sinar/hr-censorship-dashboard#27]
For some use cases such as an annual report for a country, researchers would like to be able to see event context when looking at specific periods.

eg. when if viewing a yearly, monthly or daily view, are there significant events during these period relevant to that country?

Event could be single date or a period of days.

* 2018-07-29 Cambodian General Elections
* 2018-05-09 Malaysian General Elections
* 2018-06-09 - 2018-06-15 Civil Unrest due to Pro-Democracy Protests in Vietnam

Event Categories

* Elections
* Information Control
* Political Instability
* Visits by Government Officials
* Other

Affected Use Cases

#22 
#19

**Comment by kaerumy** [comment]
@Jeffrey04 one thing to look at here. Is it possible to extract event data from Wikidata query?

Since in theory we would only need to get a date or date range, description and a link to wikipedia, which would be more scable then to try manage entering event data.

Test case:

Query date and description of Cambodian events for July from Wikidata

**Comment by kaerumy** [comment]
Looks like it might be doable https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/queries/examples#Recent_Events

**Comment by Jeffrey04** [comment]
yes it should be doable
