### ISSUE TITLE
Home Page, Regional Overview Table

### ISSUE THREAD

**Issue by kaerumy** [Sinar/hr-censorship-dashboard#37]
![image](https://user-images.githubusercontent.com/1060743/47562911-aeeb4500-d952-11e8-927d-1980f902f183.png)

**Comment by Jeffrey04** [comment]
![screen shot 2018-11-09 at 15 41 12-fullpage](https://user-images.githubusercontent.com/46977/48256617-1cb36880-e44b-11e8-8566-6d8558343ba4.png)


this is how it currently looks like if upstream fixes their data
