### ISSUE TITLE
Country by Category Table

### ISSUE THREAD

**Issue by kaerumy** [Sinar/hr-censorship-dashboard#38]
![image](https://user-images.githubusercontent.com/1060743/47562966-e2c66a80-d952-11e8-9fb9-ac37695b03dd.png)

**Comment by Jeffrey04** [comment]
![screen shot 2018-11-09 at 15 42 18-fullpage](https://user-images.githubusercontent.com/46977/48258468-0eb41680-e450-11e8-8c8f-19b347c06a80.png)

this is the current state of the table
