### ISSUE TITLE
Quick Review of Possible UI Frameworks for use

### ISSUE THREAD

**Issue by kaerumy** [Sinar/hr-censorship-dashboard#5]
* Multilingual  (Khmer, Burmese, Thai)
* Mobile friendly
* Maintainability

Possible:

* vue.js
* angular.js
* react.js
* ...

**Comment by Jeffrey04** [comment]
unless there's special preference/need, otherwise i would use react as i am most productive with it compared to vue and angular. Not really a frontend guy, so I probably go with something i am more familiar with.

**Comment by kaerumy** [comment]
Issue #20 is a good test case, for say vue.js vs react.js try implement a radar chart with a labels in Chinese and English. Then to see if it can easily support multilingual support

**Comment by Jeffrey04** [comment]
gonna stick with react and experiment with different UI frameworks that uses react

mainly this one as it has chart support built in
https://www.primefaces.org/primereact/#/

this one isn't as fancy but it has locale support built in
https://ant.design/

this one looks enterprisey enough
https://atlaskit.atlassian.com/packages/core/progress-tracker

this is rather popular
https://react.semantic-ui.com/modules/modal

skipping material design as I can't find one with enough widgets for building dashboards
